set nocompatible
set encoding=utf-8
syntax enable 
set tabstop=4
set softtabstop=4
set expandtab
set smarttab
set number 
set relativenumber 
filetype plugin indent on  
" set wildmode=longest,list,full
" autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
set splitbelow splitright
set clipboard+=unnamedplus
set nobackup
set incsearch
" set cursorline
set termguicolors
set nowrap
set mouse=a

let &t_SI="\<Esc>[1 q"
let &t_SR="\<Esc>[4 q"
let &t_EI="\<Esc>[2 q"
" autocmd InsertEnter * set cul
" autocmd InsertLeave * set nocul 
" set guicursor+=n-v-c:blinkon0
" - entered insert mode
" set notimeout 
set ttyfast
set ttimeout
set ttimeoutlen=1
" set timeoutlen=300
set viminfofile=NONE

" Plugins
call plug#begin('~/.vim/plugged')
Plug 'sheerun/vim-polyglot'
Plug 'jiangmiao/auto-pairs'
Plug 'lervag/vimtex'
Plug 'sirver/ultisnips'
Plug 'preservim/nerdtree'
" Plug 'vim-airline/vim-airline'
" Plug 'bluz71/vim-nightfly-guicolors'
Plug 'bluz71/vim-moonfly-colors'
Plug 'bluz71/vim-moonfly-guicolors'
Plug '907th/vim-auto-save'
Plug 'tpope/vim-commentary'
call plug#end()

" set noshowmode

let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
"let g:UltiSnipsSnippetDirectories = '~/.vim/UltiSnips'

let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
" let g:vimtex_view_general_viewer = 'okular'
" let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'

let g:vimtex_compiler_latexmk_engines = {
    \ '_'                : '-xelatex',
    \ 'pdfdvi'           : '-pdfdvi',
    \ 'pdfps'            : '-pdfps',
    \ 'pdflatex'         : '-pdf',
    \ 'luatex'           : '-lualatex',
    \ 'lualatex'         : '-lualatex',
    \ 'xelatex'          : '-xelatex',
    \ 'context (pdftex)' : '-pdf -pdflatex=texexec',
    \ 'context (luatex)' : '-pdf -pdflatex=context',
    \ 'context (xetex)'  : '-pdf -pdflatex=''texexec --xtx''',
    \}

let g:auto_save_silent = 1
colorscheme moonfly
set background=dark
" let g:moonflyTransparent = v:true
let g:moonflyCursorColor = v:true
hi Normal guibg=NONE ctermbg=NONE

let mapleader = " "
nnoremap <leader>e :NERDTreeToggle<CR>
nnoremap <leader>as :AutoSaveToggle<CR>
set langmap=ΑA,ΒB,ΨC,ΔD,ΕE,ΦF,ΓG,ΗH,ΙI,ΞJ,ΚK,ΛL,ΜM,ΝN,ΟO,ΠP,QQ,ΡR,ΣS,ΤT,ΘU,ΩV,WW,ΧX,ΥY,ΖZ,αa,βb,ψc,δd,εe,φf,γg,ηh,ιi,ξj,κk,λl,μm,νn,οo,πp,qq,ρr,σs,τt,θu,ωv,ςw,χx,υy,ζz
